module.exports = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: ROS 2 Fundamentals',
      items: [
        'modules/ros2/intro',
        'modules/ros2/lesson-01',
        'modules/ros2/lesson-02',
        'modules/ros2/lesson-03',
        'modules/ros2/lesson-04',
        'modules/ros2/lesson-05',
        'modules/ros2/lesson-06',
        'modules/ros2/lesson-07',
        'modules/ros2/lesson-08',
        'modules/ros2/lesson-09',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Gazebo & Digital Twins',
      items: [
        'modules/gazebo/intro',
        'modules/gazebo/lesson-01',
        'modules/gazebo/lesson-02',
        'modules/gazebo/lesson-03',
        'modules/gazebo/lesson-04',
        'modules/gazebo/lesson-05',
        'modules/gazebo/lesson-06',
        'modules/gazebo/lesson-07',
        'modules/gazebo/lesson-08',
        'modules/gazebo/lesson-09',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: NVIDIA Isaac Sim',
      items: [
        'modules/isaac/intro',
        'modules/isaac/lesson-01',
        'modules/isaac/lesson-02',
        'modules/isaac/lesson-03',
        'modules/isaac/lesson-04',
        'modules/isaac/lesson-05',
        'modules/isaac/lesson-06',
        'modules/isaac/lesson-07',
        'modules/isaac/lesson-08',
        'modules/isaac/lesson-09',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action Models',
      items: [
        'modules/vla/intro',
        'modules/vla/lesson-01',
        'modules/vla/lesson-02',
        'modules/vla/lesson-03',
        'modules/vla/lesson-04',
        'modules/vla/lesson-05',
        'modules/vla/lesson-06',
        'modules/vla/lesson-07',
        'modules/vla/lesson-08',
        'modules/vla/lesson-09',
      ],
    },
  ],
};
