module.exports = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Chapter 1: ROS 2 Fundamentals',
      items: [
        'chapters/chapter-1-ros2/intro',
        'chapters/chapter-1-ros2/lesson-01',
        'chapters/chapter-1-ros2/lesson-02',
        'chapters/chapter-1-ros2/lesson-03',
        'chapters/chapter-1-ros2/lesson-04',
        'chapters/chapter-1-ros2/lesson-05',
        'chapters/chapter-1-ros2/lesson-06',
        'chapters/chapter-1-ros2/lesson-07',
        'chapters/chapter-1-ros2/lesson-08',
        'chapters/chapter-1-ros2/lesson-09',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 2: Gazebo & Digital Twins',
      items: [
        'chapters/chapter-2-gazebo/intro',
        'chapters/chapter-2-gazebo/lesson-01',
        'chapters/chapter-2-gazebo/lesson-02',
        'chapters/chapter-2-gazebo/lesson-03',
        'chapters/chapter-2-gazebo/lesson-04',
        'chapters/chapter-2-gazebo/lesson-05',
        'chapters/chapter-2-gazebo/lesson-06',
        'chapters/chapter-2-gazebo/lesson-07',
        'chapters/chapter-2-gazebo/lesson-08',
        'chapters/chapter-2-gazebo/lesson-09',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 3: NVIDIA Isaac Sim',
      items: [
        'chapters/chapter-3-isaac/intro',
        'chapters/chapter-3-isaac/lesson-01',
        'chapters/chapter-3-isaac/lesson-02',
        'chapters/chapter-3-isaac/lesson-03',
        'chapters/chapter-3-isaac/lesson-04',
        'chapters/chapter-3-isaac/lesson-05',
        'chapters/chapter-3-isaac/lesson-06',
        'chapters/chapter-3-isaac/lesson-07',
        'chapters/chapter-3-isaac/lesson-08',
        'chapters/chapter-3-isaac/lesson-09',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 4: Vision-Language-Action Models',
      items: [
        'chapters/chapter-4-vla/intro',
        'chapters/chapter-4-vla/lesson-01',
        'chapters/chapter-4-vla/lesson-02',
        'chapters/chapter-4-vla/lesson-03',
        'chapters/chapter-4-vla/lesson-04',
        'chapters/chapter-4-vla/lesson-05',
        'chapters/chapter-4-vla/lesson-06',
        'chapters/chapter-4-vla/lesson-07',
        'chapters/chapter-4-vla/lesson-08',
        'chapters/chapter-4-vla/lesson-09',
      ],
    },
  ],
};
